# Generated by Django 5.1.1 on 2024-12-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_codigoSucursal', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre_sucursal', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=50)),
                ('num_telefono', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
